### ISSUE TITLE
Core dump in ClipperLib::ClipperBase::AddPath()

### ISSUE THREAD

**Issue by djdelorie** [alexrj/Slic3r#3776]
### Version
git as of 2017-Mar-19
1.2.9-766-g52a94e8

### Operating system type + version
Fedora 24 x86-64

### Behavior
Load the included config, then load the included model.  3D view comes up OK, then it segfaults before the preview completes.  Core file says:
````
#5  0x00007f65badfb589 in __cxa_rethrow () at /lib64/libstdc++.so.6
#6  0x00007f65bb4202cc in ClipperLib::ClipperBase::AddPath(std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> > const&, ClipperLib::PolyType, bool) (this=0x7f6597ffdf78, pg=std::vector of length 2, capacity 2 = {...}, PolyTyp=<optimized out>, Closed=false) at src/clipper.cpp:1081
#7  0x00007f65bb41c7d1 in ClipperLib::ClipperBase::AddPaths(std::vector<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> >, std::allocator<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> > > > const&, ClipperLib::PolyType, bool) (this=this@entry=0x7f6597ffdf78, ppg=std::vector of length 1, capacity 1 = {...}, PolyTyp=PolyTyp@entry=ClipperLib::ptSubject, Closed=Closed@entry=false) at src/clipper.cpp:1228
#8  0x00007f65bb3ed635 in Slic3r::_clipper_do(ClipperLib::ClipType, std::vector<Slic3r::Polyline, std::allocator<Slic3r::Polyline> > const&, std::vector<Slic3r::Polygon, std::allocator<Slic3r::Polygon> > const&, ClipperLib::PolyFillType, bool) (clipType=clipType@entry=ClipperLib::ctDifference, subject=std::vector of length 1, capacity 1 = {...}, clip=std::vector of length 1, capacity 1 = {...}, fillType=fillType@entry=ClipperLib::pftNonZero, safety_offset_=safety_offset_@entry=false) at src/libslic3r/ClipperUtils.cpp:352
#9  0x00007f65bb3ed84a in Slic3r::_clipper_pl(ClipperLib::ClipType, std::vector<Slic3r::Polyline, std::allocator<Slic3r::Polyline> > const&, std::vector<Slic3r::Polygon, std::allocator<Slic3r::Polygon> > const&, bool) (clipType=clipType@entry=ClipperLib::ctDifference, subject=std::vector of length 1, capacity 1 = {...}, clip=std::vector of length 1, capacity 1 = {...}, safety_offset_=safety_offset_@entry=false) at src/libslic3r/ClipperUtils.cpp:388
#10 0x00007f65bb35fe42 in Slic3r::ExPolygon::contains(Slic3r::Polyline const&) const (safety_offset_=false, clip=std::vector of length 1, capacity 1 = {...}, subject=std::vector of length 1, capacity 1 = {...})
    at src/libslic3r/ClipperUtils.hpp:129
#11 0x00007f65bb35fe42 in Slic3r::ExPolygon::contains(Slic3r::Polyline const&) const (this=this@entry=0x7f65780289d0, polyline=...) at src/libslic3r/ExPolygon.cpp:102
#12 0x00007f65bb35ff8c in Slic3r::ExPolygon::contains(Slic3r::Line const&) const (this=0x7f65780289d0, line=...)
    at src/libslic3r/ExPolygon.cpp:96
#13 0x00007f65bb3788fd in Slic3r::Geometry::MedialAxis::validate_edge(boost::polygon::voronoi_edge<double> const*) (this=this@entry=0x7f6597ffe510, edge=<optimized out>, edge@entry=0x7f657803a3a0)
    at src/libslic3r/Geometry.cpp:626
#14 0x00007f65bb379334 in Slic3r::Geometry::MedialAxis::build(std::vector<Slic3r::ThickPolyline, std::allocator<Slic3r::ThickPolyline> >*) (this=this@entry=0x7f6597ffe510, polylines=polylines@entry=0x7f6597ffe4d0)
    at src/libslic3r/Geometry.cpp:514
#15 0x00007f65bb36180b in Slic3r::ExPolygon::medial_axis(double, double, std::vector<Slic3r::ThickPolyline, std::allocator<Slic3r::ThickPolyline> >*) const (this=this@entry=0x7f65780289d0, max_width=max_width@entry=1514158, min_width=min_width@entry=96000, polylines=polylines@entry=0x7f6597ffe900) at src/libslic3r/ExPolygon.cpp:196
#16 0x00007f65bb3af0fa in Slic3r::PerimeterGenerator::process() (this=this@entry=0x7f6597ffea40)
    at src/libslic3r/PerimeterGenerator.cpp:268
#17 0x00007f65bb3e07d3 in Slic3r::LayerRegion::make_perimeters(Slic3r::SurfaceCollection const&, Slic3r::SurfaceCollection*) (this=0x7f656c1f6730, slices=..., fill_surfaces=0x7f656c1f6788) at src/libslic3r/LayerRegion.cpp:65
#18 0x00007f65bb3daf5b in Slic3r::Layer::make_perimeters() (this=<optimized out>) at src/libslic3r/Layer.cpp:188
#19 0x00007f65bb4614b7 in Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*, boost::mutex*, boost::function<void (Slic3r::Layer*)>) (a0=0x7f656c085740, this=0x7f6597ffeed0) at /usr/include/boost/function/function_template.hpp:771
#20 0x00007f65bb4614b7 in Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*, boost::mutex*, boost::function<void (Slic3r::Layer*)>) (queue=0x7f65777fda40, queue_mutex=0x7f65777fd470, func=...) at src/libslic3r/libslic3r.h:85
#21 0x00007f65bb46137d in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*, boost::mutex*, boost::function<void (Slic3r::Layer*)>), boost::_bi::list3<boost::_bi::value<std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*>, boost::_bi::value<boost::mutex*>, boost::_bi::value<boost::function<void (Slic3r::Layer*)> > > > >::run() (a=<synthetic pointer>, f=
    @0x7f656c24ac08: 0x7f65bb461420 <Slic3r::_parallelize_do<Slic3r::Layer*>(std::queue<Slic3r::Layer*, std::deque<Slic3r::Layer*, std::allocator<Slic3r::Layer*> > >*, boost::mutex*, boost::function<void (Slic3r::Layer*)>)>, this=0x7f656c24ac10) at /usr/include/boost/bind/bind.hpp:398
````

#### STL/Config (.ZIP) where problem occurs
[clipper-core-bug1.zip](https://github.com/alexrj/Slic3r/files/853575/clipper-core-bug1.zip)

**Comment by alexrj** [comment]
Thank you for reporting this case, it was a numerical issue. I fixed it.
