### ISSUE TITLE
Crash with specific STL

### ISSUE THREAD

**Issue by multiplemonomials** [alexrj/Slic3r#3919]
### Version
automated dev build slic3r-master.2017.04.29.989 (from [here](http://dl.slic3r.org/dev/win/))

### Operating system type + version
Windows 10 Build 1703

### Behavior
* The latest Slic3r build crashes when loading the attached STL into the plater.  It's a kind of screwed up file, I know; I'm still a beginner with Blender.  However, when I use Slic3r 1.2.9 instead of the dev version, it loads and works fine.
* Step to Reproduce: Press `Add...` in the plater window and select the attached STL
  * Background slicing is enabled
* _Expected Results_
  * The file loads and is able to be sliced
* _Actual Results_
  * Slic3r crashes.  Backtrace from MinGW-w64 GDB follows:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000002b9bc359 in boot_Slic3r__XS ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Slic3r\XS\XS.xs.dll
(gdb) bt
#0  0x000000002b9bc359 in boot_Slic3r__XS ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Slic3r\XS\XS.xs.dll
#1  0x000000002b9bd412 in boot_Slic3r__XS ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Slic3r\XS\XS.xs.dll
#2  0x000000002b973991 in boot_Slic3r__XS ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Slic3r\XS\XS.xs.dll
#3  0x000000002b9c2ac3 in boot_Slic3r__XS ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Slic3r\XS\XS.xs.dll
#4  0x000000002b870dcf in ?? ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Slic3r\XS\XS.xs.dll
#5  0x000000006db8ecc0 in perl524!Perl_clear_defarray () from C:\Program Files\Slic3r-dev\perl524.dll
#6  0x000000006dbe43e6 in perl524!Perl_runops_standard () from C:\Program Files\Slic3r-dev\perl524.dll
#7  0x000000006db9cdcd in perl524!Perl_call_sv () from C:\Program Files\Slic3r-dev\perl524.dll
#8  0x0000000070353b9f in boot_Wx () from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Wx\Wx.xs.dll
#9  0x00000000047d3106 in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#10 0x0000000004932aee in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#11 0x0000000004933087 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#12 0x0000000004933382 in wxEvtHandler::TryHereOnly(wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#13 0x000000000493341a in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#14 0x0000000004933498 in wxEvtHandler::ProcessEvent(wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#15 0x0000000061cc0a55 in wxWindowBase::TryAfter(wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#16 0x0000000004934d9c in wxEvtHandler::SafelyProcessEvent(wxEvent&) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#17 0x0000000061af5d7b in wxButton::SendClickEvent() ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_-
--Type <return> to continue, or q <return> to quit---
core_gcc_custom.dll
#18 0x0000000061ac23ab in wxWindow::HandleCommand(unsigned short, unsigned short, HWND__*) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#19 0x0000000061acc955 in wxWindow::MSWHandleMessage(long long*, unsigned int, unsigned long long, long long) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#20 0x0000000061abc68c in wxWindow::MSWWindowProc(unsigned int, unsigned long long, long long) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#21 0x00007ffe355dbc50 in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#22 0x00007ffe355db94c in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#23 0x00007ffe355f11f3 in USER32!GetTopWindow () from C:\WINDOWS\System32\user32.dll
#24 0x00007ffe371890b4 in ntdll!KiUserCallbackDispatcher () from C:\WINDOWS\SYSTEM32\ntdll.dll
#25 0x00007ffe33d51164 in win32u!NtUserMessageCall () from C:\WINDOWS\System32\win32u.dll
#26 0x00007ffe355db060 in USER32!SendMessageW () from C:\WINDOWS\System32\user32.dll
#27 0x00007ffe355daee8 in USER32!SendMessageW () from C:\WINDOWS\System32\user32.dll
#28 0x00007ffe277d6194 in ImageList_SetBkColor ()
   from C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_108e4f62dfe5d999\comctl32.
dll
#29 0x00007ffe27804ce6 in COMCTL32!CCSetScrollInfo ()
   from C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_108e4f62dfe5d999\comctl32.
dll
#30 0x00007ffe355dbc50 in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#31 0x00007ffe355db80b in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#32 0x0000000061ac29d0 in wxWindow::MSWDefWindowProc(unsigned int, unsigned long long, long long) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#33 0x0000000061abc6b4 in wxWindow::MSWWindowProc(unsigned int, unsigned long long, long long) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#34 0x0000000061ae85bf in wxAnyButton::MSWWindowProc(unsigned int, unsigned long long, long long) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#35 0x00007ffe355dbc50 in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#36 0x00007ffe355db5cf in USER32!DispatchMessageW () from C:\WINDOWS\System32\user32.dll
#37 0x00007ffe355d6aef in USER32!IsDialogMessageW () from C:\WINDOWS\System32\user32.dll
#38 0x0000000061abfb7b in wxWindow::MSWSafeIsDialogMessage(tagMSG*) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
---Type <return> to continue, or q <return> to quit---
#39 0x0000000061abfdc9 in wxWindow::MSWProcessMessage(tagMSG*) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#40 0x0000000061b14958 in wxGUIEventLoop::PreProcessMessage(tagMSG*) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#41 0x0000000061b14821 in wxGUIEventLoop::ProcessMessage(tagMSG*) ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#42 0x0000000061b14653 in wxGUIEventLoop::Dispatch() ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxmsw310u_c
ore_gcc_custom.dll
#43 0x000000000480dc92 in wxEventLoopManual::ProcessEvents() ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#44 0x000000000480dd11 in wxEventLoopManual::DoRun() ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#45 0x000000000480da64 in wxEventLoopBase::Run() ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#46 0x00000000047d7e9a in wxAppConsoleBase::MainLoop() ()
   from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\Alien\wxWidgets\msw_3_1_0_uni_gcc_3_4\lib\wxbase310u_
gcc_custom.dll
#47 0x000000007041652b in boot_Wx () from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Wx\Wx.xs.dll
#48 0x000000007025dbc4 in ?? () from C:\PROGRA~1\SLIC3R~1\LOCAL-~1\lib\perl5\MSWin32-x64-multi-thread\auto\Wx\Wx.xs.dll
#49 0x000000006db8ecc0 in perl524!Perl_clear_defarray () from C:\Program Files\Slic3r-dev\perl524.dll
#50 0x000000006dbe43e6 in perl524!Perl_runops_standard () from C:\Program Files\Slic3r-dev\perl524.dll
#51 0x000000006dba4994 in perl_run () from C:\Program Files\Slic3r-dev\perl524.dll
#52 0x000000006dbf6f78 in perl524!RunPerl () from C:\Program Files\Slic3r-dev\perl524.dll
#53 0x00000000004019c7 in main ()
```
_Is this a new feature request?_
No

#### STL/Config (.ZIP) where problem occurs
[Raven Seal STL.zip](https://github.com/alexrj/Slic3r/files/967124/Raven.Seal.STL.zip)

**Comment by lordofhyphens** [comment]
Feed the model through service.netfabb.com.

**Comment by lordofhyphens** [comment]
In short, GIGO. 95% sure this is in admesh.

**Comment by multiplemonomials** [comment]
This does work perfectly in version 1.2.9 though.  Even if it is a messed up STL, I feel like it shouldn't crash the whole program.

**Comment by alexrj** [comment]
gdb output:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
0x0000000101212984 in stl_compare_function [inlined] () at /Users/al/Documents/git/Slic3r/xs/src/admesh/connect.c:264
264	  if(edge_a->facet_number == edge_b->facet_number) {
```

**Comment by alexrj** [comment]
I agree Slic3r shouldn't crash even with garbage. However I wasn't able to fix this admesh bug, so I'll leave it open.
