### ISSUE TITLE
crash in Slic3r::ExPolygon::simplify_p when reloading an stl

### ISSUE THREAD

**Issue by djdelorie** [alexrj/Slic3r#4052]
### Version
git head 13f121e3d952cca33b1ee5fdd73c12d85bf54d0e

### Operating system type + version
Fedora 24 x86-64

### Behavior
Load the attached config and model
Select the model
Object->reload from disk
segfaults

#0  0x00007fffee732054 in Slic3r::ExPolygon::simplify_p(double) const (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/6.3.1/bits/stl_vector.h:656
#1  0x00007fffee732054 in Slic3r::ExPolygon::simplify_p(double) const (this=this@entry=0x1, tolerance=tolerance@entry=0.5) at src/libslic3r/ExPolygon.cpp:151
#2  0x00007fffee73256b in Slic3r::ExPolygon::simplify(double) const (this=this@entry=0x1, tolerance=tolerance@entry=0.5) at src/libslic3r/ExPolygon.cpp:176
#3  0x00007fffee732625 in Slic3r::ExPolygon::simplify(double, std::vector<Slic3r::ExPolygon, std::allocator<Slic3r::ExPolygon> >*) const (this=this@entry=0x1, tolerance=tolerance@entry=0.5, expolygons=expolygons@entry=0x7fffd37fda90) at src/libslic3r/ExPolygon.cpp:183
#4  0x00007fffee7df0e1 in Slic3r::ExPolygonCollection::simplify(double) (this=0x414e990, tolerance=tolerance@entry=0.5) at src/libslic3r/ExPolygonCollection.cpp:90
#5  0x00007fffee5bae9a in XS_Slic3r__ExPolygon__Collection_simplify(PerlInterpreter*, CV*) (my_perl=<optimized out>, cv=<optimized out>)
    at /usr/bin/perl -MExtUtils::XSpp::Cmd -e xspp -- -t "/envy/dj/rostock_max/Slic3r/xs/xsp/typemap.xspt"  "/envy/dj/rostock_max/Slic3r/xs/xsp/ExPolygonCollection.xsp":98
#6  0x00007ffff7ac92fb in Perl_pp_entersub () at /lib64/libperl.so.5.22
#7  0x00007ffff7ac1f66 in Perl_runops_standard () at /lib64/libperl.so.5.22
#8  0x00007ffff7a45f66 in Perl_call_sv () at /lib64/libperl.so.5.22
#9  0x00007fffeeee97de in S_jmpenv_run (my_perl=my_perl@entry=0x6611990, action=action@entry=0, thread=thread@entry=0x3b6f540, len_p=len_p@entry=0x7fffd37fdf14, exit_app_p=exit_app_p@entry=0x7fffd37fdf0c, exit_code_p=exit_code_p@entry=0x7fffd37fdf10) at threads.xs:497
#10 0x00007fffeeee99ff in S_ithread_run (arg=0x3b6f540) at threads.xs:591

[simplify-bug.zip](https://github.com/alexrj/Slic3r/files/1116296/simplify-bug.zip)

**Comment by VanessaE** [comment]
Just a bump -- trying to reload a model still causes a crash, as of commit 202a90ff903be5b61fca317c6b614af0d5f34d8a (I did not take a backtrace).
