### ISSUE TITLE
C++ CLI Slic3r export_svg ignores PrintConfig defaults

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#4139]
Ran the minimal CLI with --export-svg on a debug build, got a coredump.
````
./slic3r 3DBenchy.stl --export-svg
````
````
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
````
````
0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f3dbd2fc3fa in __GI_abort () at abort.c:89
#2  0x0000560b10b7e18d in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x0000560b10af6c46 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000560b10af6c91 in std::terminate() ()
#5  0x0000560b10af6bd9 in __cxa_throw ()
#6  0x0000560b10af691c in operator new(unsigned long) ()
#7  0x0000560b109eec9e in __gnu_cxx::new_allocator<Slic3r::SLAPrint::Layer>::allocate (this=0x7ffc4ee112a8, __n=33554432)
    at /usr/include/c++/6/ext/new_allocator.h:104
#8  0x0000560b109edb0e in std::allocator_traits<std::allocator<Slic3r::SLAPrint::Layer> >::allocate (__a=..., __n=33554432)
    at /usr/include/c++/6/bits/alloc_traits.h:436
#9  0x0000560b109ec776 in std::_Vector_base<Slic3r::SLAPrint::Layer, std::allocator<Slic3r::SLAPrint::Layer> >::_M_allocate (this=0x7ffc4ee112a8, __n=33554432)
    at /usr/include/c++/6/bits/stl_vector.h:170
#10 0x0000560b109ea500 in std::vector<Slic3r::SLAPrint::Layer, std::allocator<Slic3r::SLAPrint::Layer> >::_M_emplace_back_aux<Slic3r::SLAPrint::Layer>(Slic3r::SLAPrint::Layer&&) (this=0x7ffc4ee112a8, __args#0=<unknown type in /mnt/fiver/slic3r/src/slic3r, CU 0x31f336, DIE 0x371b2c>) at /usr/include/c++/6/bits/vector.tcc:412
#11 0x0000560b109e85be in std::vector<Slic3r::SLAPrint::Layer, std::allocator<Slic3r::SLAPrint::Layer> >::emplace_back<Slic3r::SLAPrint::Layer>(Slic3r::SLAPrint::Layer&&) (this=0x7ffc4ee112a8, __args#0=<unknown type in /mnt/fiver/slic3r/src/slic3r, CU 0x31f336, DIE 0x371b2c>) at /usr/include/c++/6/bits/vector.tcc:101
#12 0x0000560b109e6a1c in std::vector<Slic3r::SLAPrint::Layer, std::allocator<Slic3r::SLAPrint::Layer> >::push_back(Slic3r::SLAPrint::Layer&&) (
    this=0x7ffc4ee112a8, __x=<unknown type in /mnt/fiver/slic3r/src/slic3r, CU 0x31f336, DIE 0x370cc6>) at /usr/include/c++/6/bits/stl_vector.h:933
#13 0x0000560b109e13f5 in Slic3r::SLAPrint::slice (this=0x7ffc4ee11190) at /home/lenox/slic3r/xs/src/libslic3r/SLAPrint.cpp:42
#14 0x0000560b1091d17f in main (argc=3, argv=0x7ffc4ee11ac8) at /home/lenox/slic3r/src/slic3r.cpp:134
````
STL (really anything will do).
https://github.com/alexrj/Slic3r/files/1343013/4130.zip

Looks like the configuration object loaded by slice() is zeroed out instead of using the defaults from PrintConfig.cpp

**Comment by lordofhyphens** [comment]
Test config from #4121 https://github.com/alexrj/Slic3r/files/1291501/test.zip
